### ISSUE TITLE
NLP Part 2: once you have loaded in a json, use an NLP API to preform some anylisis on the body text

### ISSUE THREAD

**Issue by HazelHilbert** [HazelHilbert/Legislative-Drafting-NLP#17]
This is were we will have to discuss and choose which nlp api we want to use. Probably for this week, we will just use a prexisting model like one from OpenAPI.

**Comment by aagroome** [comment]
Currently I'm using free credits of ChatGPT's API. The Python script returns citations it finds in the text provided
